// Generated by CoffeeScript 1.6.2
var EditorWithTags;

EditorWithTags = function(options) {
  var self;

  this.elem = $("<div>").addClass("editor-with-tags");
  this.input = $("<div>").addClass("input");
  this.menu = $("<div>").addClass("menu");
  this.elem.append(this.input, this.menu);
  self = this;
  this.input.focus(this.focus.bind(self));
  this.input.blur(this.blur.bind(self));
  this.input.keydown(this.onkeydown.bind(self));
  this.input.keyup(this.onkeyup.bind(self));
  this.events = new EventEmitter;
};

EditorWithTags.prototype = {
  contructor: EditorWithTags,
  text: function(value) {
    return this.elem.find(".input").text(value);
  },
  focus: function() {
    console.log("focus");
    return this.elem.addClass("focus");
  },
  blur: function() {
    return this.elem.removeClass("focus");
  },
  onkeydown: function(event) {
    var _ref;

    console.log(event.keyCode);
    if ((_ref = event.keyCode) === 13 || _ref === 38 || _ref === 40) {
      switch (event.keyCode) {
        case 13:
          this.hitEnter(event);
          break;
        case 38:
          this.hitUp(event);
          break;
        case 40:
          this.hitDown(event);
      }
      event.preventDefault();
      return false;
    }
    return this.events.emit("keydown", event);
  },
  keydown: function(callback) {
    return this.events.on("keydown", callback);
  },
  keyup: function(callback) {
    return this.events.on("keyup", callback);
  },
  onkeyup: function(event) {
    return this.events.emit("keyup", event);
  },
  optionHTML: function(text) {
    return "<div class='option'>" + text + "</div>";
  },
  renderMenu: function(list) {
    return this.menu.html(list.map(this.optionHTML).join(""));
  },
  hitEnter: function(event) {
    return console.log(event);
  },
  hitUp: function(event) {
    return console.log(event);
  },
  hitDown: function(event) {
    return console.log(event);
  },
  replaceHTML: function(html) {
    return this.input.html(html);
  },
  getHTML: function() {
    return this.input.html();
  }
};
