// Generated by CoffeeScript 1.6.2
var duplicate;

duplicate = function(string, times) {
  var output, _i, _results;

  output = "";
  (function() {
    _results = [];
    for (var _i = 1; 1 <= times ? _i <= times : _i >= times; 1 <= times ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this).forEach(function() {
    return output += string;
  });
  return output;
};

$(function() {
  var demo;

  console.log("started");
  demo = new EditorWithTags;
  console.log(demo);
  $("#target").prepend(demo.elem);
  demo.text(duplicate("demo for test", 3));
  demo.renderMenu(["a", "b"]);
  demo.keydown(function() {
    return console.log("keydown");
  });
  demo.keyup(function() {});
  return console.log(demo instanceof EditorWithTags);
});
