// Generated by CoffeeScript 1.6.2
var duplicate;

duplicate = function(string, times) {
  var output, _i, _results;

  output = "";
  (function() {
    _results = [];
    for (var _i = 1; 1 <= times ? _i <= times : _i >= times; 1 <= times ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this).forEach(function() {
    return output += string;
  });
  return output;
};

$(function() {
  var demo;

  console.log("started");
  demo = new EditorWithTags;
  demo.suggest({
    "@": ["today", "torrow", "next week", "昨天", "今天", "明天"],
    "^": ["list a", "list b", "列表3", "列表 4"]
  });
  console.log(demo);
  $("#target").prepend(demo.elem);
  console.log(demo instanceof EditorWithTags);
  return demo.elem.find(".input").click();
});
